### ISSUE TITLE
neovim error

### ISSUE THREAD

**Issue by laikahaskell** [Keyitdev/dotfiles#4]
Hi,
After running the arch script on my system (manjaro) I get the following error upon starting nvim:

`Error detected while processing /home/laika/.config/nvim/init.lua: E5113: Error while calling lua chunk: /home/laika/.config/nvim/init.lua:25: Failed to load core.autocmds  /home/laika/.config/nvim/lua/core/autocmds.lua:9: attempt to call local 'augroup' (a nil value) stack traceback:         [C]: in function 'error'         /home/laika/.config/nvim/init.lua:25: in main chunk Error detected while processing BufReadPost Autocommands for "*": E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load. lua:142: Vim(source):E5113: Error while calling lua chunk: ...te/pack/packer/opt/Comment.nvim/after/plugin/Comment.lua:1: attempt to index field 'keymap' (a nil value) stack traceback:         [C]: in function 'cmd'         ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>         [string ":lua"]:1: in main chunk`

PS, This is my first time submitting a github issue, so if I need to add any more info or format my entry better, please let me know

**Comment by Keyitdev** [comment]
I think this is a problem, with nvim. To solve try running:
```sh
sudo pacman -Sy
yay -S neovim
rm -frd $HOME/.config/nvim
git clone --depth 1 https://github.com/kabinspace/AstroVim.git $HOME/.config/nvim
nvim +PackerSync
```
then press enter
and then press 'q'
you are ready to go (I hope)
PS, Other things work fine?

**Comment by laikahaskell** [comment]
Ah, I should have realized it was a neovim issue and not with your configs. 
The issue persists after your steps, unfortunately, and I will probably have to scrape some forums about it.
And yes, everything else so far works! This is an awesome set of configurations. Thank you!

**Comment by Keyitdev** [comment]
I know this may sound obvious, but I want to point out that this is a problem with the neovim configuration, not with neovim itself.
If this neovim ([AstroVim](https://github.com/AstroNvim/AstroNvim)) configuration does not work for you, you can try other neovim configurations such as:
https://github.com/NvChad/NvChad
https://github.com/LunarVim/LunarVim
https://github.com/CosmicNvim/CosmicNvim
I think you will find something suitable for you.
I am glad you like it.
